version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jaisenbe58r/jenkins-docker
    ports:
      - "8080:8080"
    volumes:
      - $HOME:/home
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - net
networks:
  net: